# Версия схемы, которую мы используем.
# Зависит от установленной версии docker
# https://docs.docker.com/compose/compose-file/
version: "3"
services:
  frontend:
    build:
      context: ./frontend/survey-platform/.
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend/interactive-survey-platform/.
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgresql123
      - DB_NAME=poll
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgresql123
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: poll
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
